name: actions

on:
  push:
    branches:    
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: write git info
        run: echo $(git show --pretty=format:"%ci") $(git rev-parse --short HEAD) | head -1 > git_info
      # 登陆docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      # 设置 buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      # 构建与发布
      - name: Build and push
        if: ${{ github.ref_name == 'main' }}
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_USERNAME }}/my_bot:latest
      - name: Build and push
        if: ${{ github.ref_name != 'main' }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_USERNAME }}/my_bot:${{ github.ref_name }}
      # 完成
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}